query sku($identifier: SKUUniqueIdentifier ){
  sku(identifier: $identifier)
  @context(provider: "vtex.catalog-graphql"){
    name,
    images{
      url
    },
    product{
      linkId,
      brand{
        name
      }
    },
    specifications{
      product{
        value,
        field{
          name
        }
      }
    }
  }
  }
